config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :posts
  resources :comments
  resources :users
  # resources :sessions

  post '/logout', to: 'users#destroy'




get '/login', to: 'sessions#new', as: 'login'
post '/sessions', to: 'sessions#create', as: 'sessions'
# post '/logout', to: 'sessions#destroy', as: 'logout'

end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post 
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'



end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user

  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :posts
  validates :username, uniqueness: true
  has_many :sent_messages, :class_name => 'Message', :foreign_key => 'sender_id'
  has_many :received_messages, :class_name => 'Message', :foreign_key => 'receiver_id'
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    # byebug
    @comment = Comment.create(content:params[:content],post_id: params[:post_id],user_id:session[:id])
    # byebug
    redirect_to post_path(@comment.post)

  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    # byebug
    @text = Message.create(mess_params(:content,:sender_id,:receiver_id))
    post_id = params[:message][:post_id]
    flash[:message] = "Private message sent!"
    redirect_to post_path(post_id)
  end

  private

  def mess_params(*args)
    params.require(:message).permit(args)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @user = User.find(session[:id])
    @posts = Post.all
  end

  def new
    @user = User.find(session[:id])
    @post = Post.new
  end

  def show
    # byebug
    @message = Message.new 
    @post = Post.find(params[:id])
  end

  def create
    # uploaded_io = params[:post][:img_url]
     # byebug
    # picture = File.open(Rails.root.join(‘public’, ‘uploads’, uploaded_io.original_filename), ‘wb’) do |file|
    #   file.write(uploaded_io.read)
    @post = Post.create(
      title: params[:post][:title],
      recipe: params[:post][:recipe],
      img_url: params[:post][:img_url],
      user_id: session[:id])
      # byebug
    redirect_to post_path(@post)
  end



   # def post_params
   #   params.require(:post).permit(:title, :recipe, :img_url, user_id: session[:id])
   # end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @user = User.new
  end

  def create

    user = User.find_by(username: params[:user][:username])
      # byebug
    # user.password = params[:user][:password]
    if user && user.authenticate(params[:user][:password])
      session[:id] = user.id
      # binding.pry
      redirect_to user_path(user)
    else
      flash[:errors] = ["invalid username or password"]
      redirect_to "/login"
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # @user = User.find(session[:id])
    @user = User.new
    # @users = User.all
  end

  def show
    # byebug
    @user = User.find(session[:id])

  end

  def create
    # byebug
    @user = User.create(user_params)
    @user.password = params[:user][:password]
    if @user.valid?
        session[:id] = @user.id
      redirect_to user_path(@user)
    else
      # byebug
      render 'index'
    end

  end

  def destroy
    session.delete :id
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :img_url, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MichelinMeals</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<header>
  <nav>
     <%= link_to "My Profile", user_path(@user) %>
  </nav>
</header>

<h1>Hi <%= @user.username %>, here are all the posts from the Michelin Meals Community! </h1>

<ul>
  <% @posts.all.each do |p| %>
  <li>
    <%= link_to p.title, post_path(p) %>
  </li>
  <% end %>
</ul>

<div class="pusher">
  <div class="ui inverted vertical masthead center aligned segment">

    <!-- <div class="ui container">
      <div class="ui large secondary inverted pointing menu">
        <a class="toc item">
          <i class="sidebar icon"></i>
        </a>
        <a class="active item">Home</a>
        <a class="item">Work</a>
        <a class="item">Company</a>
        <a class="item">Careers</a>

      </div>
    </div> -->

    <div class="ui text container">
      <h1 class="ui inverted header">
        Michelin Meals
      </h1>
      <h2>Eat what you love.</h2>
      <h3 color="white"><%= link_to "My Profile", user_path(@user) %></h3>
    </div>

  </div>



  <iframe width="560" height="315" src="https://www.youtube.com/embed/0SPwwpruGIA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

app/views/posts/new.html.erb
<%= form_for @post, :class => 'ui form' do |f| %>
  <div class="field">
<label>Title</label>
<%= f.text_field :title, class: "form-control" %>
</div>
<br>
<div class="field">
<label>Recipe</label>
<%= f.text_area :recipe, class: "form-control", :width => '200px' %>
</div>
<br>
<div class="field">
<label>Image URL</label>
<%= f.text_field :img_url, class: "form_control" %>
</div>
<br>
<%= f.submit "Create Post", :class => 'ui button' %>
<% end %>

<br>
 <%= link_to "My Profile", user_path(@user), :class => 'ui button' %>

<!-- <form class="ui form">
  <div class="field">
    <label>First Name</label>
    <input type="text" name="first-name" placeholder="First Name">
  </div>
  <div class="field">
    <label>Last Name</label>
    <input type="text" name="last-name" placeholder="Last Name">
  </div>
  <div class="field">
    <div class="ui checkbox">
      <input type="checkbox" tabindex="0" class="hidden">
      <label>I agree to the Terms and Conditions</label>
    </div>
  </div>
  <button class="ui button" type="submit">Submit</button>
</form> -->

app/views/posts/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Michelin Meals</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href= <%= user_path %>> My Profile <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href= <%= posts_path %> >Community Blogs</a>
      </li>
    </ul>

  </div>
</nav>




<h1> <%= @post.title %> </h1>

<p> <%= @post.recipe %> </p>

<div>
  <img src="<%= @post.img_url %>" alt="" height="500" width="500">
</div>

<p> Recipe by <%= @post.user.username  %> </p>




<% @post.comments.each do |c| %>
<div class="ui comments">
  <h3 class="ui dividing header">Comments</h3>
  <div class="comment">
    <a class="avatar">
      <img src= <%= c.user.img_url %>>
    </a>
    <div class="content">
      <a class="author"> <%= c.user.username %>  </a>
      <div class="metadata">
        <span class="date"> <%= Time.now.strftime('%c') %> </span>
      </div>
      <div class="text">
        <%= c.content %>
      </div>
      <div class="actions">
        <a class="reply">Reply</a>
      </div>
    </div>
  </div>
<% end %>

  <form class="ui reply form" action="/comments" method="post">
    <div class="field">
      <input type="text" name="content">
      <!-- <textarea> -->
      <input type="hidden" name="post_id" value= <%= @post.id %>>




      <!-- </textarea> -->
    </div>
    <div class="ui blue labeled submit icon button">
      <i class="icon edit"></i> <input type="submit" name="submit" value="Add Comment">

    </div>
  </form>
</div>

<% if flash[:message] %>
  <%= flash[:message] %>
<% end %>
<h2>Send a private message to <%= @post.user.username %></h2>
<%= form_for @message do |f| %>
  <%= f.text_field :content %>
  <%= f.hidden_field :sender_id, :value => session[:id] %>
  <%= f.hidden_field :receiver_id, :value => @post.user.id %>
  <%= f.hidden_field :post_id, :value => @post.id %>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1> Welcome to Michelin Meals</h1>

<h2>Please Sign Up</h2>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <br>
  <%= f.label :img_url %>
  <%= f.text_field :img_url %>
  <br>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <br>
  <%= f.submit "Sign up" %>
<% end %>

<%= link_to 'Click here if you are an existing user', '/login' %>

app/views/users/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href=<%= posts_path %>>Michelin Meals</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href= <%= posts_path %>> See all posts <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href= <%= new_post_path %>> Create New Post <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">







      </li>
    </ul>

  </div>
</nav>

<%= form_tag '/logout', method: "post" do %>
<%= submit_tag "Sign Out" %>
<% end %>


























<h1>Welcome to Michelin Meals <%= @user.username %> </h1>





<h2> My Food Blogs and Recipes </h2>

<% @user.posts.each do |post| %> </p>
<p> <%= link_to post.title, post_path(post), :class => 'ui button' %> </p>
<% end %>


<div class="ui card">
  <div class="image">
    <img src= <%= @user.img_url %>>
  </div>
  <div class="content">
    <a class="header"> <%= @user.username %></a>
    <div class="meta">
      <span class="date"></span>
    </div>
    <div class="description">
      Michelin Meals member
    </div>
  </div>
  <div class="extra content">
    <a>
      <i class="user icon"></i>
      <%= @user.received_messages.count %> messages in your inbox
    </a>
  </div>
</div>


<li style="width: 500px" class="list-group-item active">Received Messages:</li>
<% @user.received_messages.reverse_each do |u| %>
  <ul class="list-group">

    <div style="width: 400px" class="ui message">
    <div class="header">
      <p>From: <%= u.sender.username %></p>
    </div>
    <p><%= u.content %></p>
  </div>
  </ul>
  <% end %>






      <li style="width: 500px" class="list-group-item active">Sent Messages:</li>
      <% @user.sent_messages.reverse_each do |u| %>
        <ul class="list-group">

          <div style="width: 400px" class="ui message">
          <div class="header">
            <p>To: <%= u.receiver.username %> </p>
          </div>
          <p><%= u.content %></p>
        </div>
        </ul>
        <% end %>